### ISSUE TITLE
How2setup

### ISSUE THREAD

**Issue by skyynet** [terafin/mqtt-netatmo-bridge#22]
Hi,

I use a netatmo weather station providing weather data inside, outside & with additional module rain.
I'd like to write their data to mqtt.
I have a mqtt broker running on my Synology NAS and would like to setup the docker file.
Unfortunately there's no documentation, yet.

What are the startup parameters?
Which environmental vars may be setup?
I'd assume to somehow pass MQTT_IP, MQTT_PORT, NETATMO_CLIENT_ID & NETATMO_CLIENT_SECRET

Information highly appreciated.

Thanks from Germany

**Comment by terafin** [comment]
Hi there, thanks for reaching out! I updated the docs on the readme, with some examples, please let me know if that doesn't work for you!

**Comment by skyynet** [comment]
Works right from the start. I'll post a how to setup for Synology NAS on my homepage at skyynet.de/netatmo in a few days. English translation will follow at  skyynet.de/e-netatmo

Thanks for writing the bridge!

**Comment by terafin** [comment]
Great! Let me know and I can happily link to it here!

**Comment by skyynet** [comment]
Hi, just did it. See https://skyynet.de/netatmo for the German and https://skyynet.de/e-netatmo for the English version.

**Comment by terafin** [comment]
Thank you, linked :)
